spring.application.name=tracer

spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require&pgbouncer=true&prepareThreshold=0
spring.datasource.username=postgres.ifyvupxuaxotrtawkors
spring.datasource.password=group4databas
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Reduce pool size to stay within Supabase limits
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1