spring.application.name=tracer

# Supabase Cloud PostgreSQL connection
spring.datasource.url=jdbc:postgresql://db.snphgynncwojiazksdka.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=QVg3EIGM1nmKBDJd
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect