spring.application.name=tracer

#postgreSQL Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/testDB
#The following will be used when cloud hosting works
#spring.datasource.url=jdbc:postgresql://db.snphgynncwojiazksdka.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1234
#This password is the randomly generated one for the supabase server
#spring.datasource.password=QVg3EIGM1nmKBDJd
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA/Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect